### PR TITLE
Major update on all functions and vignette

### PR DESCRIPTION
**Pull request by estellad**
add a function input on which assay to plot, and fixed ploting on a continuous scale with viridis - p + scale_color_viridis_c() for plotMolecules(spe, palette = "viridis").

### CODE REVIEW

**Comment by estellad** [comment]
For the package ggspavis to improve:

1. plotMolecules() to:

- have one more continuous palettes "viridis"

- to be able to specify which assay to use (e.g. for checking the effect before and after normalization)

2. plotVisium() to:

- have a better continuous palette scale called "seuratlike" in utils.R that takes the rainbow scale from blue to beige to red. The current two color gradient is very difficult to tell apart pink from blue.

**Comment by estellad** [comment]
This is ggspavis default plotVisium():
image

This is Seurat SpatialFeaturePlot(): 
image

**This is my pull request on plotVisium():**
image

**We currently have a new version to be "Pull Requested" by @senbaikang:** 
image

Please share your thoughts on how to proceed to improve the visualization of ggspavis :smile:

**Comment by estellad** [comment]
ggspavis default plotMolecules():
image
 
This pull request added two new palettes for plotMolecules():
plotMolecules(vis, molecule = "ENSG00000009307", assay = "counts", palette = "seuratlike")
image

plotMolecules(vis, molecule = "ENSG00000009307", assay = "counts", palette = "viridis")
image

**Comment by estellad** [comment]
- Added a palette similar to Seurat (blue-beige-red) and a palette option "viridis" in utils.R, 
- Making it flexible to take either categorical or continuous variables (including gene expression) on plotDimRed() and plotSpots().
- Replaced the plotQC(type = "bar") to type = "histogram" and updated the function. 
- Added more examples on plotQC() in vignette.
- Removed plotMolecules(), as it can be achieved by plotSpots. 
- Added one example of single-cell spatial CosMx data plotting using plotSpots() in vignette.

**Comment by lmweber** [comment]
Hi @estellad , thanks again for this major update, and apologies again for the delay. I'm working through the updates locally now, including all the checks and tests, and will add some commits here (from the checks and/or a few other updates) before merging the branch.

There is a Bioconductor release deadline coming up soon, so I will aim to have all this merged and pushed to Bioc in time for the next release. Thank you!

**Comment by lmweber** [comment]
Hi @estellad , thanks again for providing these updates. I have added some more commits above to integrate them all, and will now merge everything into the `devel` branch.

A few points to mention:

- I updated a number of argument names for consistency with the rest of the package, and also updated all the docs and code formatting
- Updated all the remaining packaging issues, e.g. fixing imports and DESCRIPTION file etc
- I restored the `plotMolecules()` function, since this wasn't completely redundant with the new version of `plotSpots()`. Specifically, `plotSpots()` can't easily handle an object containing a `BumpyMatrix`, like our example from the seqFISH platform. So I'll keep `plotMolecules()` in the package for now too.
- I updated the vignette and removed several sections since they were quite slow. We could put some of these parts back in again later, or alternatively show examples in the Best Practices book instead. The vignette still needs some work and I will aim to revisit it at some point later on (although not sure when).
- There are some large `.csv` files in the git history that were added and deleted. I'll try to remove these later using BFG repo-cleaner and overwrite the history in the `devel` branch, to keep the overall package / repo size small.

Thanks again for all this work. The updates will make the `ggspavis` package much more useful overall, and we will be able to use all these functions in the Best Practices book now.

**Pull request merged**
